# Generated by Django 4.0.2 on 2022-02-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('headerIdentifier', models.CharField(max_length=2)),
                ('orignatorCode', models.CharField(max_length=11)),
                ('responderCode', models.CharField(max_length=11)),
                ('fileRefernceNo', models.CharField(max_length=10)),
                ('totalNoOfRecords', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordIdentifer', models.CharField(max_length=2)),
                ('recordRefernceNo', models.CharField(max_length=15)),
                ('ifscCode', models.CharField(max_length=11)),
                ('destinationBankAccountNo', models.CharField(max_length=35)),
                ('accountValidFlag', models.CharField(max_length=2)),
                ('jointAccountFlag', models.CharField(max_length=2)),
                ('primaryPan', models.CharField(max_length=10)),
                ('secondaryPan', models.CharField(max_length=10)),
                ('primaryAccountHolderName', models.CharField(max_length=50)),
                ('secondaryAccountHolderName', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=2)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbdtapp.header')),
            ],
        ),
    ]
