# Generated by Django 3.2.12 on 2022-03-16 10:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbdtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='destinationBankAccountNo',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=35)),
        ),
        migrations.AlterField(
            model_name='records',
            name='primaryPan',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='records',
            name='secondaryPan',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
    ]
