# Generated by Django 3.2.12 on 2022-03-17 04:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbdtapp', '0002_auto_20220316_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='fileRefernceNo',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='header',
            name='filename',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='header',
            name='headerIdentifier',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2)),
        ),
        migrations.AlterField(
            model_name='header',
            name='orignatorCode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=11)),
        ),
        migrations.AlterField(
            model_name='header',
            name='responderCode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=11)),
        ),
        migrations.AlterField(
            model_name='header',
            name='totalNoOfRecords',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=6)),
        ),
        migrations.AlterField(
            model_name='records',
            name='accountType',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2)),
        ),
        migrations.AlterField(
            model_name='records',
            name='ifscCode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=11)),
        ),
        migrations.AlterField(
            model_name='records',
            name='jointAccountFlag',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2)),
        ),
        migrations.AlterField(
            model_name='records',
            name='primaryAccountHolderName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='records',
            name='recordIdentifer',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2)),
        ),
        migrations.AlterField(
            model_name='records',
            name='recordRefernceNo',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=15)),
        ),
        migrations.AlterField(
            model_name='records',
            name='secondaryAccountHolderName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
